const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.jumpthru,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{Спрайт: 0},
	{Платформер: 0},
	{СледитьЗа: 0},
	{Спрайт2: 0},
	{Твёрдый: 0},
	{Спрайт3: 0},
	{Спрайт4: 0},
	{Спрайт5: 0},
	{Спрайт6: 0},
	{СквознаяПлатформа: 0},
	{Спрайт7: 0},
	{Спрайт8: 0},
	{Спрайт9: 0},
	{Спрайт10: 0},
	{Спрайт11: 0},
	{Спрайт12: 0},
	{Спрайт13: 0},
	{Спрайт14: 0},
	{Спрайт15: 0},
	{Спрайт16: 0},
	{Спрайт17: 0},
	{Спрайт18: 0},
	{Спрайт19: 0},
	{Спрайт20: 0},
	{Спрайт21: 0},
	{Спрайт22: 0},
	{Спрайт23: 0},
	{Спрайт24: 0},
	{Спрайт25: 0},
	{Спрайт26: 0},
	{Спрайт27: 0},
	{Спрайт28: 0},
	{Якорь: 0},
	{Текст: 0},
	{Спрайт29: 0},
	{Спрайт30: 0},
	{Спрайт31: 0},
	{Спрайт32: 0},
	{Спрайт33: 0},
	{Спрайт34: 0},
	{Спрайт35: 0},
	{Спрайт36: 0},
	{Спрайт37: 0},
	{Спрайт38: 0},
	{Спрайт39: 0},
	{Спрайт40: 0},
	{Спрайт41: 0},
	{баланс: 0}
];

self.InstanceType = {
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	Спрайт13: class extends self.ISpriteInstance {},
	Спрайт14: class extends self.ISpriteInstance {},
	Спрайт15: class extends self.ISpriteInstance {},
	Спрайт16: class extends self.ISpriteInstance {},
	Спрайт17: class extends self.ISpriteInstance {},
	Спрайт18: class extends self.ISpriteInstance {},
	Спрайт19: class extends self.ISpriteInstance {},
	Спрайт20: class extends self.ISpriteInstance {},
	Спрайт21: class extends self.ISpriteInstance {},
	Спрайт22: class extends self.ISpriteInstance {},
	Спрайт23: class extends self.ISpriteInstance {},
	Спрайт24: class extends self.ISpriteInstance {},
	Спрайт25: class extends self.ISpriteInstance {},
	Спрайт26: class extends self.ISpriteInstance {},
	Спрайт27: class extends self.ISpriteInstance {},
	Спрайт28: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	Спрайт29: class extends self.ISpriteInstance {},
	Спрайт30: class extends self.ISpriteInstance {},
	Спрайт31: class extends self.ISpriteInstance {},
	Спрайт32: class extends self.ISpriteInstance {},
	Спрайт33: class extends self.ISpriteInstance {},
	Спрайт34: class extends self.ISpriteInstance {},
	Спрайт35: class extends self.ISpriteInstance {},
	Спрайт36: class extends self.ISpriteInstance {},
	Спрайт37: class extends self.ISpriteInstance {},
	Спрайт38: class extends self.ISpriteInstance {},
	Спрайт39: class extends self.ISpriteInstance {},
	Спрайт40: class extends self.ISpriteInstance {},
	Спрайт41: class extends self.ISpriteInstance {}
}